formatters:
  rubocop_link_formatter:
    require: rubocop/formatter/link_formatter
    path_prefix: "https://github.com/rubocop/ruby-style-guide"
    url_template: "%{path_prefix}%{cop_name}.md"

rubocop:
  # Map of RuboCop severity level to Pronto severity level
  severities:
    refactor: info
    warning: error

  # Enable suggestions
  suggestions: true

  enabled: true
  command: ["rubocop", "-f", "json"]
  formatter: rubocop_link_formatter