rubocop:
  # Map of RuboCop severity level to Pronto severity level
  severities:
    refactor: info
    warning: error

  # Enable suggestions
  suggestions: true

  enabled: true
  command: ["rubocop", "-f", "json"]
  formatter: rubocop_link_formatter