name: RuboCop

on:
  pull_request:
    branches: ["main" , "dev"]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RuboCop
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - run: gem install rubocop
      - name: Run RuboCop
        run: rubocop
